<a href="https://colab.research.google.com/github/chalumuru-hemanth/DataScience-numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#pip install numpy


In [2]:
import numpy as np


In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
b = np.array([[1,2,3,4],
              [1,2,3,4]])

In [5]:
a.ndim

1

In [10]:
# for dimensions
b.ndim

2

In [12]:
b.shape #rows, columns

(2, 4)

In [14]:
b.size

8

In [15]:
b.nbytes

64

In [17]:
c = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
print(c[0,2]) #row, column

3


In [27]:
c[:,2]

array([ 3,  7, 11])

In [34]:
f = np.array([[[[1,2],
             [3,4],
             [5,6],
             [7,8]]]])
f.ndim
f

array([[[[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]]])

In [37]:
r = np.random.rand(4,2)
r


array([[0.48629761, 0.00923948],
       [0.33019909, 0.88461594],
       [0.85751354, 0.32194631],
       [0.02991814, 0.37947462]])

In [39]:
o = np.identity(4)

In [40]:
o

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
# make a copy of ab so that it does not effect the original data
ab = np.array([1,2,3,4])
ba = ab.copy()
ba[0] = 12
print(ba)
print(ab)

[12  2  3  4]
[1 2 3 4]


In [47]:
#multiply the array with 2
ab * 2

array([2, 4, 6, 8])